# Generated by Django 3.0.3 on 2020-06-03 12:43

from django.db import migrations, models
import django.db.models.deletion
import lembaga.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institusi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lembaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('gambar', models.ImageField(upload_to=lembaga.models.upload_location)),
                ('jenis_pelayanan', models.CharField(max_length=255)),
                ('deskripsi_singkat', models.TextField()),
                ('beneficaries', models.CharField(max_length=1024)),
                ('alamat', models.CharField(max_length=1024)),
                ('praktikum_ke', models.IntegerField()),
                ('institusi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lembaga.Institusi')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lembaga.Tema')),
            ],
        ),
    ]
