# Generated by Django 3.0.3 on 2020-06-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lembaga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institusi',
            name='nama',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tema',
            name='nama',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
