# Generated by Django 3.1.3 on 2021-06-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lembaga', '0006_auto_20210425_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='lembaga',
            name='last_activity',
            field=models.IntegerField(blank=True, null=True, verbose_name='last activity'),
        ),
    ]
