# Generated by Django 3.1.3 on 2021-06-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lembaga', '0007_lembaga_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lembaga',
            name='last_activity',
        ),
    ]
