# Generated by Django 3.0.3 on 2020-06-03 12:43

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lembaga', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('role', models.CharField(max_length=50, verbose_name='role')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, verbose_name='nama')),
            ],
            options={
                'verbose_name': 'periode',
                'verbose_name_plural': 'periode',
            },
        ),
        migrations.CreateModel(
            name='SupervisorSekolah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(blank=True, max_length=12, verbose_name='nip')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_sekolah', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'supervisor_sekolah',
                'verbose_name_plural': 'supervisor_sekolah',
            },
        ),
        migrations.CreateModel(
            name='SupervisorLembaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=150, verbose_name='jabatan')),
                ('lembaga', models.ForeignKey(default='Tidak ada lembaga', on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_lembaga', to='lembaga.Lembaga')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_lembaga', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'supervisor_lembaga',
                'verbose_name_plural': 'supervisor_lembaga',
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_code', models.CharField(blank=True, max_length=11, verbose_name='organization_code')),
                ('npm', models.CharField(blank=True, max_length=10, verbose_name='npm')),
                ('faculty', models.CharField(blank=True, max_length=128, verbose_name='faculty')),
                ('major', models.CharField(blank=True, max_length=128, verbose_name='major')),
                ('program', models.CharField(blank=True, max_length=128, verbose_name='program')),
                ('periode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periode', to='authentication.Periode')),
                ('supervisor_lembaga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa', to='authentication.SupervisorLembaga', to_field='user')),
                ('supervisor_sekolah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa', to='authentication.SupervisorSekolah', to_field='user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mahasiswa',
                'verbose_name_plural': 'mahasiswa',
            },
        ),
        migrations.CreateModel(
            name='KoordinatorKuliah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=12, verbose_name='nip')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='koordinator_kuliah', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'koordinator_kuliah',
                'verbose_name_plural': 'koordinator_kuliah',
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=12, verbose_name='nip')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'administrator',
                'verbose_name_plural': 'administrator',
            },
        ),
    ]
