# Generated by Django 3.1.3 on 2020-11-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201113_0949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
