# Generated by Django 3.1.3 on 2021-05-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorlembaga',
            name='lastlogin',
            field=models.DateField(blank=True, null=True, verbose_name='Last login'),
        ),
    ]
