# Generated by Django 3.1.3 on 2021-05-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_supervisorlembaga_lastlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorlembaga',
            name='lastlogin',
            field=models.DateField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
