# Generated by Django 3.1.3 on 2021-05-24 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20210524_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisorlembaga',
            name='lastlogin',
        ),
    ]
